CREATE TABLE TAB_LOTE_AVES (
    ID_LOTE            INTEGER NOT NULL,
    DESCRICAO          VARCHAR(100),
    DATA_ENTRADA       DATE,
    QUANTIDADE_INICIAL INTEGER,
    PESO_MEDIO_GERAL   DECIMAL(10,2),
    CONSTRAINT PK_TAB_LOTE_AVES PRIMARY KEY (ID_LOTE)
);

CREATE TABLE TAB_PESAGEM (
    ID_PESAGEM         INTEGER NOT NULL,
    ID_LOTE_FK         INTEGER NOT NULL,
    DATA_PESAGEM       DATE,
    PESO_MEDIO         DECIMAL(10,2),
    QUANTIDADE_PESADA  INTEGER,
    CONSTRAINT PK_TAB_PESAGEM PRIMARY KEY (ID_PESAGEM),
    CONSTRAINT FK_PESAGEM_LOTE FOREIGN KEY (ID_LOTE_FK)
        REFERENCES TAB_LOTE_AVES (ID_LOTE)
);

CREATE TABLE TAB_MORTALIDADE (
    ID_MORTALIDADE     INTEGER NOT NULL,
    ID_LOTE_FK         INTEGER NOT NULL,
    DATA_MORTALIDADE   DATE,
    QUANTIDADE_MORTA   INTEGER,
    OBSERVACAO         VARCHAR(255),
    CONSTRAINT PK_TAB_MORTALIDADE PRIMARY KEY (ID_MORTALIDADE),
    CONSTRAINT FK_MORTALIDADE_LOTE FOREIGN KEY (ID_LOTE_FK)
        REFERENCES TAB_LOTE_AVES (ID_LOTE)
);
