CREATE OR ALTER PROCEDURE PRCD_INSERIR_PESAGEM (P_ID_LOTE INTEGER, P_DATA_PESAGEM DATE, P_PESO_MEDIO DECIMAL(10,2), P_QUANTIDADE_PESADA INTEGER)
AS
DECLARE VARIABLE V_QUANTIDADE_INICIAL INTEGER;
  DECLARE VARIABLE V_QUANTIDADE_PESADA INTEGER;
  DECLARE VARIABLE V_PESO_MEDIO_GERAL DECIMAL(10,2);
BEGIN
  SELECT QUANTIDADE_INICIAL
    FROM TAB_LOTE_AVES
   WHERE ID_LOTE = :P_ID_LOTE
    INTO :V_QUANTIDADE_INICIAL;

  IF (:P_QUANTIDADE_PESADA > :V_QUANTIDADE_INICIAL) THEN
    EXCEPTION EX_QTD_PESADA;

  INSERT INTO TAB_PESAGEM (
    ID_PESAGEM,
    ID_LOTE_FK,
    DATA_PESAGEM,
    PESO_MEDIO,
    QUANTIDADE_PESADA
  )
  VALUES (
    NEXT VALUE FOR SEQ_PESAGEM,
    :P_ID_LOTE,
    :P_DATA_PESAGEM,
    :P_PESO_MEDIO,
    :P_QUANTIDADE_PESADA
  );

  SELECT COALESCE(SUM(QUANTIDADE_PESADA), 0)
    FROM TAB_PESAGEM
   WHERE ID_LOTE_FK = :P_ID_LOTE
    INTO :V_QUANTIDADE_PESADA;

  IF (:V_QUANTIDADE_PESADA > 0) THEN
  BEGIN
    SELECT ROUND(SUM(PESO_MEDIO * QUANTIDADE_PESADA) / :V_QUANTIDADE_PESADA, 2)
      FROM TAB_PESAGEM
     WHERE ID_LOTE_FK = :P_ID_LOTE
      INTO :V_PESO_MEDIO_GERAL;

    UPDATE TAB_LOTE_AVES
       SET PESO_MEDIO_GERAL = :V_PESO_MEDIO_GERAL
     WHERE ID_LOTE = :P_ID_LOTE;
  END
END