CREATE OR ALTER PROCEDURE PRCD_INSERIR_MORTALIDADE (P_ID_LOTE INTEGER, P_DATA_MORTALIDADE DATE, P_QUANTIDADE_MORTA INTEGER, P_OBSERVACAO VARCHAR(255))
RETURNS (
	P_PERCENTUAL DECIMAL(10,2)
)
AS
DECLARE VARIABLE V_QUANTIDADE_INICIAL INTEGER;
DECLARE VARIABLE V_QUANTIDADE_MORTA   INTEGER;
BEGIN
  SELECT QUANTIDADE_INICIAL
    FROM TAB_LOTE_AVES
   WHERE ID_LOTE = :P_ID_LOTE
    INTO :V_QUANTIDADE_INICIAL;

  SELECT COALESCE(SUM(QUANTIDADE_MORTA), 0)
    FROM TAB_MORTALIDADE
   WHERE ID_LOTE_FK = :P_ID_LOTE
    INTO :V_QUANTIDADE_MORTA;

  IF ((:V_QUANTIDADE_MORTA + :P_QUANTIDADE_MORTA) > :V_QUANTIDADE_INICIAL) THEN
    EXCEPTION EX_MORTALIDADE;

  INSERT INTO TAB_MORTALIDADE (
    ID_MORTALIDADE,
    ID_LOTE_FK,
    DATA_MORTALIDADE,
    QUANTIDADE_MORTA,
    OBSERVACAO
  )
  VALUES (
    NEXT VALUE FOR SEQ_MORTALIDADE,
    :P_ID_LOTE,
    :P_DATA_MORTALIDADE,
    :P_QUANTIDADE_MORTA,
    :P_OBSERVACAO
  );

  SELECT COALESCE(SUM(QUANTIDADE_MORTA), 0)
    FROM TAB_MORTALIDADE
   WHERE ID_LOTE_FK = :P_ID_LOTE
    INTO :V_QUANTIDADE_MORTA;

  P_PERCENTUAL = ROUND((:V_QUANTIDADE_MORTA * 100.0) / :V_QUANTIDADE_INICIAL, 2);

  SUSPEND;
END